# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/camera/lib/lane/postprocessor/denseline/denseline_postprocessor.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/camera/lib/lane/postprocessor/denseline/denseline_postprocessor.proto',
  package='apollo.perception.camera.lane',
  syntax='proto2',
  serialized_pb=_b('\nXmodules/perception/camera/lib/lane/postprocessor/denseline/denseline_postprocessor.proto\x12\x1d\x61pollo.perception.camera.lane\"\x80\x02\n\x16LanePostprocessorParam\x12\x1f\n\x14omit_bottom_line_num\x18\x01 \x01(\x05:\x01\x33\x12&\n\x19laneline_map_score_thresh\x18\x02 \x01(\x02:\x03\x30.4\x12(\n\x1blaneline_point_score_thresh\x18\x03 \x01(\x02:\x03\x30.6\x12(\n\x1dlaneline_point_min_num_thresh\x18\x04 \x01(\x05:\x01\x32\x12 \n\x15\x63\x63_valid_pixels_ratio\x18\x05 \x01(\x02:\x01\x32\x12\'\n\x1blaneline_reject_dist_thresh\x18\x06 \x01(\x02:\x02\x35\x30')
)




_LANEPOSTPROCESSORPARAM = _descriptor.Descriptor(
  name='LanePostprocessorParam',
  full_name='apollo.perception.camera.lane.LanePostprocessorParam',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='omit_bottom_line_num', full_name='apollo.perception.camera.lane.LanePostprocessorParam.omit_bottom_line_num', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=3,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='laneline_map_score_thresh', full_name='apollo.perception.camera.lane.LanePostprocessorParam.laneline_map_score_thresh', index=1,
      number=2, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.4),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='laneline_point_score_thresh', full_name='apollo.perception.camera.lane.LanePostprocessorParam.laneline_point_score_thresh', index=2,
      number=3, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(0.6),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='laneline_point_min_num_thresh', full_name='apollo.perception.camera.lane.LanePostprocessorParam.laneline_point_min_num_thresh', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=2,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='cc_valid_pixels_ratio', full_name='apollo.perception.camera.lane.LanePostprocessorParam.cc_valid_pixels_ratio', index=4,
      number=5, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(2),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='laneline_reject_dist_thresh', full_name='apollo.perception.camera.lane.LanePostprocessorParam.laneline_reject_dist_thresh', index=5,
      number=6, type=2, cpp_type=6, label=1,
      has_default_value=True, default_value=float(50),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=124,
  serialized_end=380,
)

DESCRIPTOR.message_types_by_name['LanePostprocessorParam'] = _LANEPOSTPROCESSORPARAM
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

LanePostprocessorParam = _reflection.GeneratedProtocolMessageType('LanePostprocessorParam', (_message.Message,), dict(
  DESCRIPTOR = _LANEPOSTPROCESSORPARAM,
  __module__ = 'modules.perception.camera.lib.lane.postprocessor.denseline.denseline_postprocessor_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.camera.lane.LanePostprocessorParam)
  ))
_sym_db.RegisterMessage(LanePostprocessorParam)


# @@protoc_insertion_point(module_scope)
