# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: modules/perception/lidar/lib/object_filter_bank/proto/filter_bank_config.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='modules/perception/lidar/lib/object_filter_bank/proto/filter_bank_config.proto',
  package='apollo.perception.lidar',
  syntax='proto2',
  serialized_pb=_b('\nNmodules/perception/lidar/lib/object_filter_bank/proto/filter_bank_config.proto\x12\x17\x61pollo.perception.lidar\"\'\n\x10\x46ilterBankConfig\x12\x13\n\x0b\x66ilter_name\x18\x01 \x03(\t')
)




_FILTERBANKCONFIG = _descriptor.Descriptor(
  name='FilterBankConfig',
  full_name='apollo.perception.lidar.FilterBankConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filter_name', full_name='apollo.perception.lidar.FilterBankConfig.filter_name', index=0,
      number=1, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=107,
  serialized_end=146,
)

DESCRIPTOR.message_types_by_name['FilterBankConfig'] = _FILTERBANKCONFIG
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

FilterBankConfig = _reflection.GeneratedProtocolMessageType('FilterBankConfig', (_message.Message,), dict(
  DESCRIPTOR = _FILTERBANKCONFIG,
  __module__ = 'modules.perception.lidar.lib.object_filter_bank.proto.filter_bank_config_pb2'
  # @@protoc_insertion_point(class_scope:apollo.perception.lidar.FilterBankConfig)
  ))
_sym_db.RegisterMessage(FilterBankConfig)


# @@protoc_insertion_point(module_scope)
